<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01-Delete_Note_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a6de4cc3-e0ae-4e93-be52-98322bb35efc</testSuiteGuid>
   <testCaseLink>
      <guid>f24be7a5-5f6d-4836-a1ca-4bce25f34651</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/5.Delete Note/TC01-Delete_Text_Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efc3ff84-f942-484f-bfb7-eda225522cbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1de3e1e7-2c46-460f-8969-2bb4628ab6a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/5.Delete Note/TC02-Delete_Checklist_Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d81524c0-527d-4715-8364-5f2485ffd809</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
