<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS02-Create_Note_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>aca575c9-6419-4bcd-9d16-8e740126dab0</testSuiteGuid>
   <testCaseLink>
      <guid>4fb23455-012e-4e49-837d-dad0fb21a090</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1.Creating Note/TC01-Successfully_Create Simple_Text Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>160cd884-c3a4-47ef-bc80-679cd59f2159</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4ee9bcc-2acf-45e4-ab81-e40e74424934</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/1.Creating Note/TC02-Successfully_Create_Checklist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab743f4d-9262-4ec6-823e-103b6981c7be</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
