<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01-Edit_Note_Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>37da243c-4091-494c-b2b5-f289a7565ede</testSuiteGuid>
   <testCaseLink>
      <guid>91ed41e8-dc66-4b9f-9f7b-3df6f2f635b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.Edit Note/TC01-Edit_Text_Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44804d28-51d1-49c9-b638-62e2869501a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe6e83e-31b7-4dae-aec0-1dcab7b1bcd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2dc64102-86dc-44ba-b3a9-bbc4484d0ea8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.Edit Note/TC02-Edit_Checklist_Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab8b4d08-e995-401b-9146-2ac5169042b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1db5ffae-41ef-4b4a-bc77-4fdd3cb4c7a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d37f3ab-516f-4622-980b-40cbc35dbd0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.Edit Note/TC03-Revert_Note</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e82a57-2cdf-4983-9e64-3ae89b6ddadf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>881aad87-3e7d-4d97-b167-a65f0946d3fc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
